apiVersion: apps/v1
kind: Deployment
metadata:
  name: vlearning-api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vlearning-api-gateway
  template:
    metadata:
      labels:
        app: vlearning-api-gateway
    spec:
      containers:
        - name: vlearning-api-gateway
          image: javedmv/api-gateway:latest  # Replace with your actual image name
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: api-config
---
apiVersion: v1
kind: Service
metadata:
  name: vlearning-api-gateway
spec:
  selector:
    app: vlearning-api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
