apiVersion: apps/v1
kind: Deployment
metadata:
  name: vlearning-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vlearning-auth-service
  template:
    metadata:
      labels:
        app: vlearning-auth-service
    spec:
      containers:
        - name: vlearning-auth-service
          image: javedmv/auth-service:latest # Replace with your actual Docker image name
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: auth-config
---
apiVersion: v1
kind: Service
metadata:
  name: vlearning-auth-service3
spec:
  selector:
    app: vlearning-auth-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001