apiVersion: apps/v1
kind: Deployment
metadata:
  name: vlearning-chat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vlearning-chat-service
  template:
    metadata:
      labels:
        app: vlearning-chat-service
    spec:
      containers:
        - name: vlearning-chat-service
          image: javedmv/chat-service:latest # Replace with your actual Docker image name
          ports:
            - containerPort: 3005
          envFrom:
            - configMapRef:
                name: chat-config
---
apiVersion: v1
kind: Service
metadata:
  name: vlearning-chat-service
spec:
  selector:
    app: vlearning-chat-service
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
