apiVersion: apps/v1
kind: Deployment
metadata:
  name: vlearning-course-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vlearning-course-srv
  template:
    metadata:
      labels:
        app: vlearning-course-srv
    spec:
      containers:
        - name: vlearning-course-srv
          image: javedmv/course-srv:latest  # Replace with your actual Docker image name
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: course-config
---
apiVersion: v1
kind: Service
metadata:
  name: vlearning-course-srv
spec:
  selector:
    app: vlearning-course-srv
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
