apiVersion: apps/v1
kind: Deployment
metadata:
  name: vlearning-payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vlearning-payment-srv
  template:
    metadata:
      labels:
        app: vlearning-payment-srv
    spec:
      containers:
        - name: vlearning-payment-srv
          image: javedmv/payment-srv:latest # Replace with your actual Docker image
          ports:
            - containerPort: 3004
          envFrom:
            - configMapRef:
                name: payment-config
---
apiVersion: v1
kind: Service
metadata:
  name: vlearning-payment-srv
spec:
  selector:
    app: vlearning-payment-srv
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
