apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vlearning-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Disable automatic SSL redirect
    nginx.ingress.kubernetes.io/rewrite-target: /$2    # Rewrite path to remove prefix
    nginx.ingress.kubernetes.io/use-regex: "true"      # Enable regex in paths
spec:
  rules:
  - host: welearning.online
    http:
      paths:
      - path: /auth(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: vlearning-api-gateway
            port:
              number: 3000
      - path: /course(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: vlearning-api-gateway
            port:
              number: 3000
      - path: /notification(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: vlearning-api-gateway
            port:
              number: 3000
      - path: /payment(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: vlearning-api-gateway
            port:
              number: 3000
      - path: /chat(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: vlearning-api-gateway
            port:
              number: 3000
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: vlearning-frontend
            port:
              number: 80
  # If you're using HTTPS, add TLS configuration here
  # tls:
  # - hosts:
  #   - welearning.online
  #   secretName: welearning-tls