apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vlearning-ingress
  annotations:
    nginx.ingress.kubernetes.io/enable-websocket: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: welearning.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vlearning-api-gateway
                port:
                  number: 3000
          - path: /webhook
            pathType: Prefix
            backend:
              service:
                name: vlearning-payment-srv
                port:
                  number: 3004
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: vlearning-chat-service
                port:
                  number: 3005
