apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vlearning-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: welearning.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vlearning-api-gateway
                port:
                  number: 3000

          - path: /webhook
            pathType: Prefix
            backend:
              service:
                name: vlearning-payment-srv
                port:
                  number: 3004

          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: vlearning-chat-service
                port:
                  number: 3005

          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: vlearning-auth-service
                port:
                  number: 3001

          - path: /course
            pathType: Prefix
            backend:
              service:
                name: vlearning-course-srv
                port:
                  number: 3003

          - path: /notification
            pathType: Prefix
            backend:
              service:
                name: vlearning-notification-service
                port:
                  number: 3002
