apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vlearning-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Origin: https://v-learning-client-5r8j.vercel.app";
      more_set_headers "Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS";
      more_set_headers "Access-Control-Allow-Headers: Authorization, Content-Type, X-Requested-With";
      more_set_headers "Access-Control-Allow-Credentials: true";
      
      if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' 'https://v-learning-client-5r8j.vercel.app' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, X-Requested-With' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        return 204;
      }
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  rules:
  - host: welearning.online
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: vlearning-api-gateway
            port:
              number: 3000
